package main

import (
	_ "github.com/environ-project/environ-server/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

type MessageResponse struct {
	Message string `json:"message"`
}

// @title Environ Server API
// @version 0.1
// @description This is a Environ server.

// @contact.name Environ
// @contact.email kghnkl0103@gmail.com

// @host mark.dev.tjlabscorp.com:8080
func main() {
	ginRouter := gin.Default()
	ginRouter.GET("/", IndexHandler)
	ginRouter.GET("/ping", PingPongHandler)
	ginRouter.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	ginRouter.Run(":8080")
}

// IndexHandler godoc
// @Summary Index
// @Produce json
// @Success 200 {object} MessageResponse
// @Router / [get]
func IndexHandler(c *gin.Context) {
	c.JSON(200, gin.H{
		"message": "Hello World",
	})
}

// PingPongHandler godoc
// @Summary PingPong
// @Produce json
// @Success 200 {object} MessageResponse
// @Router /ping [get]
func PingPongHandler(c *gin.Context) {
	c.JSON(200, gin.H{
		"message": "pong",
	})
}
